apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow-server
  namespace: mlops-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlflow-server
  template:
    metadata:
      labels:
        app: mlflow-server
    spec:
      containers:
      - name: mlflow-server
        image: python:3.9-slim
        ports:
        - containerPort: 5000
        env:
        - name: AWS_ACCESS_KEY_ID
          value: mlops
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: minio-secret
              key: password
              namespace: mlops-data
        - name: MLFLOW_S3_ENDPOINT_URL
          value: http://minio.mlops-data:9000
        - name: POSTGRES_USER
          value: mlops
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgresql-secret
              key: password
              namespace: mlops-data
        - name: POSTGRES_HOST
          value: postgresql.mlops-data
        - name: POSTGRES_PORT
          value: "5432"
        - name: POSTGRES_DB
          value: mlops
        command:
        - /bin/bash
        - -c
        - |
          pip install mlflow psycopg2-binary boto3 &&
          mlflow server \
            --backend-store-uri postgresql://mlops:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB} \
            --artifacts-destination s3://mlflow-artifacts/ \
            --serve-artifacts \
            --host 0.0.0.0 \
            --port 5000
        resources:
          requests:
            cpu: 200m
            memory: 512Mi
          limits:
            cpu: 1000m
            memory: 2Gi
        livenessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 60
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: mlflow-server
  namespace: mlops-system
spec:
  selector:
    app: mlflow-server
  ports:
  - port: 5000
    targetPort: 5000
  type: ClusterIP